# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tatm.proto\"4\n\x13\x41uthenticateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03pin\x18\x02 \x01(\x05\"H\n\x14\x41uthenticateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x10\n\x08\x41uthCode\x18\x03 \x01(\t\"H\n\x0fWithdrawRequest\x12\x10\n\x08\x41uthCode\x18\x01 \x01(\t\x12\r\n\x05units\x18\x02 \x01(\x03\x12\x14\n\x0c\x64\x65nomination\x18\x03 \x01(\x05\"T\n\rWithdrawReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05units\x18\x03 \x01(\x03\x12\x14\n\x0c\x64\x65nomination\x18\x04 \x01(\x05\"G\n\x0e\x44\x65positRequest\x12\x10\n\x08\x41uthCode\x18\x01 \x01(\t\x12\r\n\x05units\x18\x02 \x01(\x03\x12\x14\n\x0c\x64\x65nomination\x18\x03 \x01(\x05\"S\n\x0c\x44\x65positReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05units\x18\x03 \x01(\x03\x12\x14\n\x0c\x64\x65nomination\x18\x04 \x01(\x05\"\"\n\x0e\x42\x61lanceRequest\x12\x10\n\x08\x41uthCode\x18\x01 \x01(\t\"S\n\x0c\x42\x61lanceReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05units\x18\x03 \x01(\x03\x12\x14\n\x0c\x64\x65nomination\x18\x04 \x01(\x05\x32\xce\x01\n\x03\x41tm\x12=\n\x0c\x41uthenticate\x12\x14.AuthenticateRequest\x1a\x15.AuthenticateResponse\"\x00\x12.\n\x08Withdraw\x12\x10.WithdrawRequest\x1a\x0e.WithdrawReply\"\x00\x12+\n\x07\x44\x65posit\x12\x0f.DepositRequest\x1a\r.DepositReply\"\x00\x12+\n\x07\x42\x61lance\x12\x0f.BalanceRequest\x1a\r.BalanceReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATEREQUEST._serialized_start=13
  _AUTHENTICATEREQUEST._serialized_end=65
  _AUTHENTICATERESPONSE._serialized_start=67
  _AUTHENTICATERESPONSE._serialized_end=139
  _WITHDRAWREQUEST._serialized_start=141
  _WITHDRAWREQUEST._serialized_end=213
  _WITHDRAWREPLY._serialized_start=215
  _WITHDRAWREPLY._serialized_end=299
  _DEPOSITREQUEST._serialized_start=301
  _DEPOSITREQUEST._serialized_end=372
  _DEPOSITREPLY._serialized_start=374
  _DEPOSITREPLY._serialized_end=457
  _BALANCEREQUEST._serialized_start=459
  _BALANCEREQUEST._serialized_end=493
  _BALANCEREPLY._serialized_start=495
  _BALANCEREPLY._serialized_end=578
  _ATM._serialized_start=581
  _ATM._serialized_end=787
# @@protoc_insertion_point(module_scope)
